-- Create Districts table
CREATE TABLE "Districts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NameAz" character varying(100) NOT NULL,
    "NameEn" character varying(100) NOT NULL,
    "NameRu" character varying(100) NOT NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CityId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" uuid,
    "UpdatedBy" uuid,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" uuid,
    CONSTRAINT "PK_Districts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Districts_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES "Cities" ("Id") ON DELETE RESTRICT
);

-- Add DistrictId column to PetAds
ALTER TABLE "PetAds" ADD COLUMN "DistrictId" integer;

-- Create indexes on Districts
CREATE INDEX "IX_Districts_CityId" ON "Districts" ("CityId");
CREATE INDEX "IX_Districts_DisplayOrder" ON "Districts" ("DisplayOrder");
CREATE INDEX "IX_Districts_IsActive" ON "Districts" ("IsActive");
CREATE INDEX "IX_Districts_IsDeleted" ON "Districts" ("IsDeleted");
CREATE INDEX "IX_Districts_NameAz" ON "Districts" ("NameAz");

-- Create index on PetAds.DistrictId
CREATE INDEX "IX_PetAds_DistrictId" ON "PetAds" ("DistrictId");

-- Add FK from PetAds to Districts
ALTER TABLE "PetAds" ADD CONSTRAINT "FK_PetAds_Districts_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES "Districts" ("Id") ON DELETE SET NULL;

-- Record this migration in EF history so it won't try to apply again
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260212120655_AddDistricts', '8.0.11');
