INSERT INTO "Districts" ("NameAz", "NameEn", "NameRu", "CityId", "DisplayOrder", "IsActive", "IsDeleted", "CreatedAt") VALUES
-- Bakı rayonları
('Səbail rayonu', 'Sabail district', 'Сабаильский район', 1, 1, true, false, NOW()),
('Nəsimi rayonu', 'Nasimi district', 'Насиминский район', 1, 2, true, false, NOW()),
('Nizami rayonu', 'Nizami district', 'Низаминский район', 1, 3, true, false, NOW()),
('Yasamal rayonu', 'Yasamal district', 'Ясамальский район', 1, 4, true, false, NOW()),
('Nərimanov rayonu', 'Narimanov district', 'Наримановский район', 1, 5, true, false, NOW()),
('Binəqədi rayonu', 'Binagadi district', 'Бинагадинский район', 1, 6, true, false, NOW()),
('Xətai rayonu', 'Khatai district', 'Хатаинский район', 1, 7, true, false, NOW()),
('Sabunçu rayonu', 'Sabunchu district', 'Сабунчинский район', 1, 8, true, false, NOW()),
('Suraxanı rayonu', 'Surakhani district', 'Сураханский район', 1, 9, true, false, NOW()),
('Qaradağ rayonu', 'Garadagh district', 'Гарадагский район', 1, 10, true, false, NOW()),
('Xəzər rayonu', 'Khazar district', 'Хазарский район', 1, 11, true, false, NOW()),
('Pirallahı rayonu', 'Pirallahi district', 'Пираллахинский район', 1, 12, true, false, NOW()),

-- Bakı qəsəbələri
('Badamdar', 'Badamdar', 'Бадамдар', 1, 13, true, false, NOW()),
('Bayıl', 'Bayil', 'Баил', 1, 14, true, false, NOW()),
('Bibiheybət', 'Bibiheybat', 'Бибиэйбат', 1, 15, true, false, NOW()),
('Şıxov', 'Shikhov', 'Шыхов', 1, 16, true, false, NOW()),
('Sahil', 'Sahil', 'Сахил', 1, 17, true, false, NOW()),
('İçərişəhər', 'Icherisheher', 'Ичеришехер', 1, 18, true, false, NOW()),
('8-ci kilometr', '8th kilometer', '8-й километр', 1, 19, true, false, NOW()),
('Əhmədli', 'Ahmadli', 'Ахмедлы', 1, 20, true, false, NOW()),
('Həzi Aslanov', 'Hazi Aslanov', 'Гази Асланов', 1, 21, true, false, NOW()),
('Keşlə', 'Keshla', 'Кешля', 1, 22, true, false, NOW()),
('Yeni Günəşli', 'Yeni Gunashli', 'Новый Гюнешли', 1, 23, true, false, NOW()),
('Köhnə Günəşli', 'Kohna Gunashli', 'Старый Гюнешли', 1, 24, true, false, NOW()),
('Masazır', 'Masazir', 'Масазыр', 1, 25, true, false, NOW()),
('Lökbatan', 'Lokbatan', 'Лёкбатан', 1, 26, true, false, NOW()),
('Hövsan', 'Hovsan', 'Гёвсан', 1, 27, true, false, NOW()),
('Zabrat', 'Zabrat', 'Забрат', 1, 28, true, false, NOW()),
('Bakıxanov', 'Bakikhanov', 'Бакиханов', 1, 29, true, false, NOW()),
('Balaxanı', 'Balakhani', 'Балаханы', 1, 30, true, false, NOW()),
('Bilgəh', 'Bilgah', 'Бильгях', 1, 31, true, false, NOW()),
('Binə', 'Bina', 'Бина', 1, 32, true, false, NOW()),
('Buzovna', 'Buzovna', 'Бузовна', 1, 33, true, false, NOW()),
('Digah', 'Digah', 'Дигях', 1, 34, true, false, NOW()),
('Fatmayı', 'Fatmayi', 'Фатмаи', 1, 35, true, false, NOW()),
('Kürdəxanı', 'Kurdakhani', 'Кюрдаханы', 1, 36, true, false, NOW()),
('Maştağa', 'Mashtaga', 'Маштага', 1, 37, true, false, NOW()),
('Mərdəkan', 'Mardakan', 'Мардакян', 1, 38, true, false, NOW()),
('Nardaran', 'Nardaran', 'Нардаран', 1, 39, true, false, NOW()),
('Pirşağı', 'Pirshagi', 'Пиршаги', 1, 40, true, false, NOW()),
('Ramana', 'Ramana', 'Рамана', 1, 41, true, false, NOW()),
('Şağan', 'Shagan', 'Шаган', 1, 42, true, false, NOW()),
('Şüvəlan', 'Shuvelan', 'Шувелян', 1, 43, true, false, NOW()),
('Türkan', 'Turkan', 'Тюркян', 1, 44, true, false, NOW()),
('Yeni Suraxanı', 'Yeni Surakhani', 'Новый Сурахани', 1, 45, true, false, NOW()),
('Zirə', 'Zira', 'Зиря', 1, 46, true, false, NOW()),
('Ələt', 'Alat', 'Алят', 1, 47, true, false, NOW()),
('Sahil qəsəbəsi', 'Sahil settlement', 'Посёлок Сахиль', 1, 48, true, false, NOW()),
('Sulutəpə', 'Sulutepe', 'Сулутепе', 1, 49, true, false, NOW()),
('Yeni Ramana', 'Yeni Ramana', 'Новая Рамана', 1, 50, true, false, NOW()),
('Biləcəri', 'Bilajari', 'Биладжари', 1, 51, true, false, NOW()),
('Xırdalan', 'Khirdalan', 'Хырдалан', 1, 52, true, false, NOW()),
('Hökmə li', 'Hokmali', 'Хёкмели', 1, 53, true, false, NOW()),
('Mehdiabad', 'Mehdiabad', 'Мехдиабад', 1, 54, true, false, NOW()),
('Novxanı', 'Novkhani', 'Новханы', 1, 55, true, false, NOW()),
('Qobustan', 'Gobustan', 'Гобустан', 1, 56, true, false, NOW()),
('Puta', 'Puta', 'Пута', 1, 57, true, false, NOW()),
('Qaraçuxur', 'Garachukhur', 'Гарачухур', 1, 58, true, false, NOW()),
('Yeni Həyat', 'Yeni Hayat', 'Новая Жизнь', 1, 59, true, false, NOW()),
('28 May', '28 May', '28 Мая', 1, 60, true, false, NOW()),
('Həsən Əliyev (Razin)', 'Hasan Aliyev (Razin)', 'Гасан Алиев (Разин)', 1, 61, true, false, NOW()),
('Müşviqabad', 'Mushvigabad', 'Мушвигабад', 1, 62, true, false, NOW()),
('Ağ şəhər (White City)', 'White City', 'Белый Город', 1, 63, true, false, NOW()),
('Bahar', 'Bahar', 'Бахар', 1, 64, true, false, NOW()),
('Dərnəgül', 'Darnagul', 'Дарнагюль', 1, 65, true, false, NOW()),
('Montin', 'Montin', 'Монтин', 1, 66, true, false, NOW()),
('NZS', 'NZS', 'НЗС', 1, 67, true, false, NOW()),
('Papanin', 'Papanin', 'Папанин', 1, 68, true, false, NOW()),
('Razin', 'Razin', 'Разин', 1, 69, true, false, NOW()),
('Əmircan', 'Amirjan', 'Амирджан', 1, 70, true, false, NOW()),
('Görədil', 'Goradil', 'Горадиль', 1, 71, true, false, NOW()),
('Corat', 'Jorat', 'Джорат', 1, 72, true, false, NOW()),
('Saray', 'Saray', 'Сарай', 1, 73, true, false, NOW()),
('Qala', 'Gala', 'Гала', 1, 74, true, false, NOW()),
('Yeni Balaxanı', 'Yeni Balakhani', 'Новые Балаханы', 1, 75, true, false, NOW()),
('Pirallahı qəsəbəsi', 'Pirallahi settlement', 'Посёлок Пираллахи', 1, 76, true, false, NOW()),
('Çilov adası', 'Chilov island', 'Остров Чилов', 1, 77, true, false, NOW());
