-- Add English and Russian localizations for Pet Breeds
BEGIN;

-- Get AppLocale IDs
-- AppLocaleId for 'en' and 'ru'

-- First, let's add English localizations (copy from AZ since they're already in English)
INSERT INTO "PetBreedLocalizations" ("PetBreedId", "AppLocaleId", "Title")
SELECT pbl."PetBreedId", 
       (SELECT "Id" FROM "AppLocales" WHERE "Code" = 'en'),
       pbl."Title"
FROM "PetBreedLocalizations" pbl
JOIN "AppLocales" al ON pbl."AppLocaleId" = al."Id"
WHERE al."Code" = 'az'
AND NOT EXISTS (
    SELECT 1 FROM "PetBreedLocalizations" existing
    JOIN "AppLocales" ex_al ON existing."AppLocaleId" = ex_al."Id"
    WHERE existing."PetBreedId" = pbl."PetBreedId" AND ex_al."Code" = 'en'
);

-- Now add Russian localizations with translations
-- Dogs (1-24)
INSERT INTO "PetBreedLocalizations" ("PetBreedId", "AppLocaleId", "Title")
SELECT pb."Id",
       (SELECT "Id" FROM "AppLocales" WHERE "Code" = 'ru'),
       CASE pb."Id"
           WHEN 1 THEN 'Лабрадор ретривер'
           WHEN 2 THEN 'Немецкая овчарка'
           WHEN 3 THEN 'Золотистый ретривер'
           WHEN 4 THEN 'Французский бульдог'
           WHEN 5 THEN 'Бигль'
           WHEN 6 THEN 'Чихуахуа'
           WHEN 7 THEN 'Померанский шпиц'
           WHEN 8 THEN 'Йоркширский терьер'
           WHEN 9 THEN 'Ши-тцу'
           WHEN 10 THEN 'Мальтийская болонка'
           WHEN 11 THEN 'Той-пудель'
           WHEN 12 THEN 'Такса'
           WHEN 13 THEN 'Бордер-колли'
           WHEN 14 THEN 'Кокер-спаниель'
           WHEN 15 THEN 'Австралийская овчарка'
           WHEN 16 THEN 'Корги'
           WHEN 17 THEN 'Бульдог'
           WHEN 18 THEN 'Сибирский хаски'
           WHEN 19 THEN 'Немецкий дог'
           WHEN 20 THEN 'Сенбернар'
           WHEN 21 THEN 'Ньюфаундленд'
           WHEN 22 THEN 'Бернский зенненхунд'
           WHEN 23 THEN 'Ротвейлер'
           WHEN 24 THEN 'Доберман'
           -- Cats (25-39)
           WHEN 25 THEN 'Мейн-кун'
           WHEN 26 THEN 'Рэгдолл'
           WHEN 27 THEN 'Персидская'
           WHEN 28 THEN 'Сиамская'
           WHEN 29 THEN 'Бенгальская'
           WHEN 30 THEN 'Британская короткошёрстная'
           WHEN 31 THEN 'Американская короткошёрстная'
           WHEN 32 THEN 'Девон-рекс'
           WHEN 33 THEN 'Сфинкс'
           WHEN 34 THEN 'Русская голубая'
           WHEN 35 THEN 'Норвежская лесная'
           WHEN 36 THEN 'Гималайская'
           WHEN 37 THEN 'Сибирская'
           WHEN 38 THEN 'Рагамаффин'
           WHEN 39 THEN 'Турецкая ангора'
           -- Rabbits (40-52)
           WHEN 40 THEN 'Голландский вислоухий'
           WHEN 41 THEN 'Нидерландский карликовый'
           WHEN 42 THEN 'Мини рекс'
           WHEN 43 THEN 'Голландский'
           WHEN 44 THEN 'Фландр'
           WHEN 45 THEN 'Польский'
           WHEN 46 THEN 'Джерси вули'
           WHEN 47 THEN 'Львиноголовый'
           WHEN 48 THEN 'Британия петит'
           WHEN 49 THEN 'Французский баран'
           WHEN 50 THEN 'Английский баран'
           WHEN 51 THEN 'Гигантская шиншилла'
           WHEN 52 THEN 'Пёстрый великан'
           -- Birds (53-64)
           WHEN 53 THEN 'Волнистый попугай'
           WHEN 54 THEN 'Канарейка'
           WHEN 55 THEN 'Зяблик'
           WHEN 56 THEN 'Неразлучник'
           WHEN 57 THEN 'Корелла'
           WHEN 58 THEN 'Конур'
           WHEN 59 THEN 'Квакер'
           WHEN 60 THEN 'Ожереловый попугай'
           WHEN 61 THEN 'Жако'
           WHEN 62 THEN 'Какаду'
           WHEN 63 THEN 'Ара'
           WHEN 64 THEN 'Амазон'
           -- Fish (65-81)
           WHEN 65 THEN 'Золотая рыбка'
           WHEN 66 THEN 'Петушок'
           WHEN 67 THEN 'Гуппи'
           WHEN 68 THEN 'Неон'
           WHEN 69 THEN 'Скалярия'
           WHEN 70 THEN 'Дискус'
           WHEN 71 THEN 'Карп кои'
           WHEN 72 THEN 'Рыба-клоун'
           WHEN 73 THEN 'Хирург'
           WHEN 74 THEN 'Помацентровые'
           WHEN 75 THEN 'Крылатка'
           WHEN 76 THEN 'Рыба-бабочка'
           WHEN 77 THEN 'Антиас'
           WHEN 78 THEN 'Золотая рыбка'
           WHEN 79 THEN 'Карп кои'
           WHEN 80 THEN 'Кардинал'
           WHEN 81 THEN 'Вьюн'
           -- Rodents (82-92)
           WHEN 82 THEN 'Морская свинка'
           WHEN 83 THEN 'Хомяк'
           WHEN 84 THEN 'Песчанка'
           WHEN 85 THEN 'Крыса'
           WHEN 86 THEN 'Мышь'
           WHEN 87 THEN 'Шиншилла'
           WHEN 88 THEN 'Дегу'
           WHEN 89 THEN 'Сирийский хомяк'
           WHEN 90 THEN 'Джунгарский хомяк'
           WHEN 91 THEN 'Хомяк Роборовского'
           WHEN 92 THEN 'Китайский хомяк'
           -- Reptiles (93-108)
           WHEN 93 THEN 'Бородатая агама'
           WHEN 94 THEN 'Леопардовый геккон'
           WHEN 95 THEN 'Реснитчатый геккон'
           WHEN 96 THEN 'Синеязыкий сцинк'
           WHEN 97 THEN 'Игуана'
           WHEN 98 THEN 'Хамелеон'
           WHEN 99 THEN 'Королевский питон'
           WHEN 100 THEN 'Маисовый полоз'
           WHEN 101 THEN 'Королевская змея'
           WHEN 102 THEN 'Удав'
           WHEN 103 THEN 'Молочная змея'
           WHEN 104 THEN 'Коробчатая черепаха'
           WHEN 105 THEN 'Среднеазиатская черепаха'
           WHEN 106 THEN 'Шпороносная черепаха'
           WHEN 107 THEN 'Расписная черепаха'
           WHEN 108 THEN 'Географическая черепаха'
           -- Horses (109-121)
           WHEN 109 THEN 'Арабская'
           WHEN 110 THEN 'Чистокровная верховая'
           WHEN 111 THEN 'Квотерхорс'
           WHEN 112 THEN 'Аппалуза'
           WHEN 113 THEN 'Мустанг'
           WHEN 114 THEN 'Клейдесдаль'
           WHEN 115 THEN 'Першерон'
           WHEN 116 THEN 'Бельгийская'
           WHEN 117 THEN 'Шайр'
           WHEN 118 THEN 'Шетлендский пони'
           WHEN 119 THEN 'Уэльский пони'
           WHEN 120 THEN 'Миниатюрная лошадь'
           WHEN 121 THEN 'Фалабелла'
           -- Farm animals (122-133)
           WHEN 122 THEN 'Курица'
           WHEN 123 THEN 'Корова'
           WHEN 124 THEN 'Овца'
           WHEN 125 THEN 'Коза'
           WHEN 126 THEN 'Индюк'
           WHEN 127 THEN 'Утка'
           WHEN 128 THEN 'Гусь'
           WHEN 129 THEN 'Шотландская высокогорная'
           WHEN 130 THEN 'Джерсейская корова'
           WHEN 131 THEN 'Ангорская коза'
           WHEN 132 THEN 'Меринос'
           WHEN 133 THEN 'Бурская коза'
           -- Exotic mammals (134-149)
           WHEN 134 THEN 'Сахарная сумчатая летяга'
           WHEN 135 THEN 'Фенек'
           WHEN 136 THEN 'Кинкажу'
           WHEN 137 THEN 'Капибара'
           WHEN 138 THEN 'Валлаби'
           WHEN 139 THEN 'Сервал'
           WHEN 140 THEN 'Палочник'
           WHEN 141 THEN 'Богомол'
           WHEN 142 THEN 'Мадагаскарский таракан'
           WHEN 143 THEN 'Жук'
           WHEN 144 THEN 'Муравьиная ферма'
           WHEN 145 THEN 'Хорёк'
           WHEN 146 THEN 'Ёж'
           WHEN 147 THEN 'Сахарная летяга'
           WHEN 148 THEN 'Шиншилла'
           WHEN 149 THEN 'Луговая собачка'
           -- Amphibians (150-165)
           WHEN 150 THEN 'Аксолотль'
           WHEN 151 THEN 'Шпорцевая лягушка'
           WHEN 152 THEN 'Красноухая черепаха'
           WHEN 153 THEN 'Тритон'
           WHEN 154 THEN 'Морская черепаха'
           WHEN 155 THEN 'Морская змея'
           WHEN 156 THEN 'Морская игуана'
           WHEN 157 THEN 'Древолаз'
           WHEN 158 THEN 'Квакша'
           WHEN 159 THEN 'Рогатая лягушка'
           WHEN 160 THEN 'Томатная лягушка'
           WHEN 161 THEN 'Африканская лягушка-бык'
           WHEN 162 THEN 'Тигровая саламандра'
           WHEN 163 THEN 'Огненная саламандра'
           WHEN 164 THEN 'Аксолотль'
           WHEN 165 THEN 'Пятнистая саламандра'
           -- Primates (166-178)
           WHEN 166 THEN 'Капуцин'
           WHEN 167 THEN 'Игрунка'
           WHEN 168 THEN 'Саймири'
           WHEN 169 THEN 'Паукообразная обезьяна'
           WHEN 170 THEN 'Макак'
           WHEN 171 THEN 'Тамарин'
           WHEN 172 THEN 'Кенгуру'
           WHEN 173 THEN 'Коала'
           WHEN 174 THEN 'Валлаби'
           WHEN 175 THEN 'Опоссум'
           WHEN 176 THEN 'Вомбат'
           WHEN 177 THEN 'Сахарная летяга'
           WHEN 178 THEN 'Тасманийский дьявол'
           -- Spiders & Scorpions (179-185)
           WHEN 179 THEN 'Чилийский розовый птицеед'
           WHEN 180 THEN 'Мексиканский красноколенный птицеед'
           WHEN 181 THEN 'Розовопалый птицеед'
           WHEN 182 THEN 'Бразильский чёрный птицеед'
           WHEN 183 THEN 'Императорский скорпион'
           WHEN 184 THEN 'Азиатский лесной скорпион'
           WHEN 185 THEN 'Пустынный скорпион'
           -- Pigs (186-195)
           WHEN 186 THEN 'Вьетнамская вислобрюхая'
           WHEN 187 THEN 'Минипиг'
           WHEN 188 THEN 'Кунекуне'
           WHEN 189 THEN 'Юлианская свинья'
           WHEN 190 THEN 'Вьетнамская вислобрюхая'
           WHEN 191 THEN 'Йоркшир'
           WHEN 192 THEN 'Дюрок'
           WHEN 193 THEN 'Гемпшир'
           WHEN 194 THEN 'Беркшир'
           WHEN 195 THEN 'Ландрас'
           -- Deer (196-201)
           WHEN 196 THEN 'Белохвостый олень'
           WHEN 197 THEN 'Чернохвостый олень'
           WHEN 198 THEN 'Благородный олень'
           WHEN 199 THEN 'Лань'
           WHEN 200 THEN 'Северный олень'
           WHEN 201 THEN 'Вапити'
           -- Bears (202-207)
           WHEN 202 THEN 'Бурый медведь'
           WHEN 203 THEN 'Чёрный медведь'
           WHEN 204 THEN 'Белый медведь'
           WHEN 205 THEN 'Гризли'
           WHEN 206 THEN 'Панда'
           WHEN 207 THEN 'Малайский медведь'
           -- Foxes (208-212)
           WHEN 208 THEN 'Рыжая лисица'
           WHEN 209 THEN 'Песец'
           WHEN 210 THEN 'Фенек'
           WHEN 211 THEN 'Серая лисица'
           WHEN 212 THEN 'Чернобурая лисица'
           -- Hedgehogs (213-215)
           WHEN 213 THEN 'Африканский карликовый ёж'
           WHEN 214 THEN 'Европейский ёж'
           WHEN 215 THEN 'Ушастый ёж'
           -- Marine mammals (216-222)
           WHEN 216 THEN 'Дельфин'
           WHEN 217 THEN 'Тюлень'
           WHEN 218 THEN 'Морской лев'
           WHEN 219 THEN 'Кит'
           WHEN 220 THEN 'Ламантин'
           WHEN 221 THEN 'Выдра'
           WHEN 222 THEN 'Морж'
           -- Mixed breeds (223-228, 230)
           WHEN 223 THEN 'Метис (собака)'
           WHEN 224 THEN 'Метис (кошка)'
           WHEN 225 THEN 'Дворняга'
           WHEN 226 THEN 'Беспородная кошка'
           WHEN 227 THEN 'Домашняя короткошёрстная'
           WHEN 228 THEN 'Не указано'
           WHEN 230 THEN 'Другой вид'
           ELSE pbl."Title"
       END
FROM "PetBreeds" pb
JOIN "PetBreedLocalizations" pbl ON pb."Id" = pbl."PetBreedId"
JOIN "AppLocales" al ON pbl."AppLocaleId" = al."Id"
WHERE al."Code" = 'az'
AND NOT EXISTS (
    SELECT 1 FROM "PetBreedLocalizations" existing
    JOIN "AppLocales" ex_al ON existing."AppLocaleId" = ex_al."Id"
    WHERE existing."PetBreedId" = pb."Id" AND ex_al."Code" = 'ru'
);

COMMIT;
