// Root layout - minimal wrapper
// All content and providers are handled by [locale]/layout.tsx
import { routing } from '@/i18n/routing';
import { cn } from '@/lib/external/utils';
import { Metadata } from 'next';
import localFont from 'next/font/local';

// Airbnb Cereal - Multilingual support for English, Azerbaijani, and Russian
const cereal = localFont({
  src: [
    {
      path: './fonts/cereal/CerealVF_W_Wght.woff2',
      weight: '300 700',
      style: 'normal',
    },
    {
      path: './fonts/cereal/CerealVF_Cyril_W_Wght.woff2',
      weight: '300 700',
      style: 'normal',
    },
    {
      path: './fonts/cereal/CerealVF_Italics_W_Wght.woff2',
      weight: '300 700',
      style: 'italic',
    },
  ],
  variable: '--font-cereal',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'puppy.az',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={cn(cereal.variable, 'antialiased')}>{children}</body>
    </html>
  );
}
